version: "3.3"
services:
  postgres_spire:
    image: "postgres"
    container_name: "spire_online"
    environment:
      - POSTGRES_USER:'postgres'
      - POSTGRES_PASSWORD:'postgres'
      - POSTGRES_DB:'spire_online'
    ports:
      - 5431:5432
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - ./postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
    driver: "local"
